nome = input("\n Entre com o nome: ")
print("\n Todo o nome: ",nome)
print("\n Primeiro caractere: ",nome[0])
print("\n Último caractere: ",nome[-1])
print("\n Primeiro ao terceiro caractere: ",nome[:3])
print("\n Quarto caractere: ",nome[3])
print("\n Todos menos o primeiro: ",nome[1:])
print("\n Os dois últimos: ",nome[-2:])
print("\n")